compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  "@storybook/core-common@*":
    dependencies:
      "@storybook/react-vite": "*"
      react: "*"
      react-dom: "*"
      vite: "*"

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-4.0.2.cjs
