nodeLinker: pnp

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-3.6.0.cjs

packageExtensions:
  "@storybook/core-common@*":
    "dependencies":
      "@storybook/react-vite": "*"
      "react": "*"
      "react-dom": "*"
      "vite": "*"
